-- CHỌN ÁO CHO ANH EM PANDA — CẤU HÌNH DỮ LIỆU DÙNG CHUNG
-- Chạy toàn bộ tệp này một lần trong Supabase SQL Editor.
-- Sau khi chạy, đổi mã CHANGE-ME-2026 theo hướng dẫn ở cuối tệp.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.jerseys (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 60),
  image_url text not null,
  code text,
  category text not null default 'Thi đấu',
  colorway text,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Nâng cấp an toàn nếu dự án đang dùng bản cũ.
alter table public.jerseys add column if not exists code text;
alter table public.jerseys add column if not exists category text not null default 'Thi đấu';
alter table public.jerseys add column if not exists colorway text;
alter table public.jerseys add column if not exists description text;
alter table public.jerseys add column if not exists is_active boolean not null default true;

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  full_name text not null check (char_length(full_name) between 2 and 80),
  print_name text check (print_name is null or char_length(print_name) <= 20),
  shirt_number integer not null check (shirt_number between 0 and 99),
  size text not null check (size in ('XS', 'S', 'M', 'L', 'XL', '2XL', '3XL')),
  note text check (note is null or char_length(note) <= 300),
  jersey_id bigint not null references public.jerseys(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'production', 'ready')),
  created_at timestamptz not null default now()
);

alter table public.registrations add column if not exists status text not null default 'pending';

create index if not exists jerseys_active_created_idx on public.jerseys(is_active, created_at desc);
create index if not exists registrations_created_at_idx on public.registrations(created_at desc);
create index if not exists registrations_jersey_id_idx on public.registrations(jersey_id);

-- Mã quản trị chỉ được kiểm tra trong cơ sở dữ liệu, không đặt trong config.js.
create table if not exists public.app_admin_settings (
  id integer primary key check (id = 1),
  secret_hash text not null,
  updated_at timestamptz not null default now()
);

alter table public.app_admin_settings enable row level security;
revoke all on public.app_admin_settings from anon, authenticated;

insert into public.app_admin_settings (id, secret_hash)
values (1, extensions.crypt('CHANGE-ME-2026', extensions.gen_salt('bf')))
on conflict (id) do nothing;

create or replace function public.admin_verify(p_admin_token text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not exists (
    select 1 from public.app_admin_settings
    where id = 1 and secret_hash = crypt(p_admin_token, secret_hash)
  ) then
    raise exception 'Mã quản trị không đúng.' using errcode = '42501';
  end if;
  return true;
end;
$$;

create or replace function public.admin_create_jersey(
  p_admin_token text,
  p_name text,
  p_image_url text,
  p_code text default null,
  p_category text default 'Thi đấu',
  p_colorway text default null,
  p_description text default null
)
returns public.jerseys
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  created_jersey public.jerseys;
begin
  if not exists (
    select 1 from public.app_admin_settings
    where id = 1 and secret_hash = crypt(p_admin_token, secret_hash)
  ) then
    raise exception 'Mã quản trị không đúng.' using errcode = '42501';
  end if;

  insert into public.jerseys (name, image_url, code, category, colorway, description)
  values (
    trim(p_name),
    p_image_url,
    nullif(trim(p_code), ''),
    coalesce(nullif(trim(p_category), ''), 'Thi đấu'),
    nullif(trim(p_colorway), ''),
    nullif(trim(p_description), '')
  )
  returning * into created_jersey;
  return created_jersey;
end;
$$;

create or replace function public.admin_set_jersey_active(
  p_admin_token text,
  p_jersey_id bigint,
  p_active boolean
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not exists (
    select 1 from public.app_admin_settings
    where id = 1 and secret_hash = crypt(p_admin_token, secret_hash)
  ) then
    raise exception 'Mã quản trị không đúng.' using errcode = '42501';
  end if;

  update public.jerseys set is_active = p_active where id = p_jersey_id;
  return found;
end;
$$;

create or replace function public.admin_set_registration_status(
  p_admin_token text,
  p_registration_id uuid,
  p_status text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not exists (
    select 1 from public.app_admin_settings
    where id = 1 and secret_hash = crypt(p_admin_token, secret_hash)
  ) then
    raise exception 'Mã quản trị không đúng.' using errcode = '42501';
  end if;
  if p_status not in ('pending', 'confirmed', 'production', 'ready') then
    raise exception 'Trạng thái không hợp lệ.' using errcode = '22023';
  end if;

  update public.registrations set status = p_status where id = p_registration_id;
  return found;
end;
$$;

revoke all on function public.admin_create_jersey(text, text, text, text, text, text, text) from public;
revoke all on function public.admin_set_jersey_active(text, bigint, boolean) from public;
revoke all on function public.admin_set_registration_status(text, uuid, text) from public;
revoke all on function public.admin_verify(text) from public;
grant execute on function public.admin_create_jersey(text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.admin_set_jersey_active(text, bigint, boolean) to anon, authenticated;
grant execute on function public.admin_set_registration_status(text, uuid, text) to anon, authenticated;
grant execute on function public.admin_verify(text) to anon, authenticated;

alter table public.jerseys enable row level security;
alter table public.registrations enable row level security;

drop policy if exists "Public can view jerseys" on public.jerseys;
create policy "Public can view jerseys" on public.jerseys for select to anon, authenticated using (true);

drop policy if exists "Public can add jerseys" on public.jerseys;

drop policy if exists "Public can view registrations" on public.registrations;
create policy "Public can view registrations" on public.registrations for select to anon, authenticated using (true);

drop policy if exists "Public can add registrations" on public.registrations;
create policy "Public can add registrations" on public.registrations for insert to anon, authenticated with check (status = 'pending');

grant usage on schema public to anon, authenticated;
grant select on public.jerseys to anon, authenticated;
grant select, insert on public.registrations to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('jersey-images', 'jersey-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view jersey images" on storage.objects;
create policy "Public can view jersey images" on storage.objects for select to anon, authenticated using (bucket_id = 'jersey-images');

drop policy if exists "Public can upload jersey images" on storage.objects;
create policy "Public can upload jersey images" on storage.objects for insert to anon, authenticated with check (bucket_id = 'jersey-images');

-- QUAN TRỌNG: chạy riêng câu dưới đây sau khi thay MAT-KHAU-MOI bằng mã mạnh của bạn.
-- update public.app_admin_settings
-- set secret_hash = extensions.crypt('MAT-KHAU-MOI', extensions.gen_salt('bf')), updated_at = now()
-- where id = 1;
